############################
#      SERVICIOS           #
############################

services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:5.7
    container_name: wp-db
    command: --ssl=0 --wait_timeout=28800 --interactive_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      TZ: ${TZ}
    healthcheck:
      # Comprueba que MySQL esté listo antes de continuar
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network
    restart: unless-stopped

  # Servicio de WordPress (PHP-FPM)
  wordpress:
    build: .
    container_name: wp-app
    environment:
      TZ: ${TZ}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      ACTIVATE_PLUGINS: ${ACTIVATE_PLUGINS}
      DISABLE_XMLRPC: ${DISABLE_XMLRPC}
      WP_DEBUG: ${WP_DEBUG}
    healthcheck:
      # Marca el contenedor como healthy solo cuando WordPress está instalado
      test: ["CMD-SHELL", "wp core is-installed --allow-root"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - wordpress_core:/var/www/html
      # Plugins personalizados (NO montes wp-content/plugins directamente)
      - ./wordpress/plugins_custom:/var/www/html/wp-content/plugins_custom
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/uploads:/var/www/html/wp-content/uploads:rw
      # Opcional: tu archivo wp-config.php personalizado
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wp_network
    restart: unless-stopped

  # Servicio de Nginx (servidor web)
  nginx:
    build:
      context: ./nginx
    container_name: nginx_wp
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      # Archivo de configuración de Nginx
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Carpeta de logs de Nginx
      - ./logs/nginx:/var/log/nginx
      # Código de WordPress en solo lectura para Nginx
      - wordpress_core:/var/www/html:ro
    environment:
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp_network

############################
#        VOLÚMENES         #
############################

volumes:
  mysql_data:      # Persistencia de datos de MySQL
  wordpress_core:  # Persistencia del código y contenido de WordPress

############################
#         REDES            #
############################

networks:
  wp_network:
    driver: bridge
