services:
  db:
    image: mysql:5.7
    container_name: wp-db
    command: --ssl=0 --wait_timeout=28800 --interactive_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      TZ: ${TZ} # Configuración de zona horaria
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      wp_network:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

  wordpress:
    build: ./wordpress
    container_name: wp-app
    volumes:
      - wordpress_core:/var/www/html
      - ./wordpress/plugins:/var/www/html/wp-content/plugins_custom
      - ./wordpress/themes:/var/www/html/wp-content/themes_custom
      - ./wordpress/uploads:/var/www/html/wp-content/uploads:rw
      - ./wordpress/themes/divi-child:/var/www/html/wp-content/themes/divi-child
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:rw
    environment:
      TZ: ${TZ} # Configuración de zona horaria
      WORDPRESS_DB_HOST: 172.28.0.2
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      ACTIVATE_PLUGINS: ${ACTIVATE_PLUGINS}
      DISABLE_XMLRPC: ${DISABLE_XMLRPC}
      WP_DEBUG: ${WP_DEBUG}
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --allow-root"]
      interval: 10s
      timeout: 5s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wp_network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - wordpress_core:/var/www/html:ro
      - ./wordpress/themes/divi-child:/var/www/html/wp-content/themes/divi-child:ro
    environment:
      TZ: ${TZ} # Configuración de zona horaria
    healthcheck:
      test: ["CMD", "curl", "-f", "http://wordpress/wp-admin/install.php"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp_network

volumes:
  mysql_data:
  wordpress_core:

networks:
  wp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24