services:
  db:
    image: mysql:5.7
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      wp_network:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    build: ./wordpress
    container_name: wp-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wordpress_core:/var/www/html
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      ACTIVATE_PLUGINS: ${ACTIVATE_PLUGINS}
      DISABLE_XMLRPC: ${DISABLE_XMLRPC}
      TZ: ${TZ}
    networks:
      - wp_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-admin/install.php || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:stable-alpine
    container_name: wp-nginx
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_core:/var/www/html:ro
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp_network

volumes:
  mysql_data:
  wordpress_core:

networks:
  wp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16