services:
  db:
    image: mysql:5.7                       # Imagen oficial de MySQL 5.7
    container_name: wp-db                  # Nombre del contenedor de base de datos
    command: --ssl=0 --wait_timeout=28800 --interactive_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Contraseña root (desde .env)
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}          # Nombre de la base de datos
      MYSQL_USER: ${WORDPRESS_DB_USER}              # Usuario de la base de datos
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}      # Contraseña del usuario
      TZ: ${TZ}                                     # Zona horaria
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql                   # Persistencia de datos de MySQL
    networks:
      - wp_network
    restart: unless-stopped

  wordpress:
    build: .
    container_name: wp-app
    environment:
      TZ: ${TZ}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      ACTIVATE_PLUGINS: ${ACTIVATE_PLUGINS}
      DISABLE_XMLRPC: ${DISABLE_XMLRPC}
      WP_DEBUG: ${WP_DEBUG}
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --allow-root"]  # Verifica si WordPress está instalado
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - wordpress_core:/var/www/html
      - ./wordpress/plugins_custom:/var/www/html/wp-content/plugins_custom
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/uploads:/var/www/html/wp-content/uploads:rw
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:rw
      - ./wordpress/security:/var/www/html/wp-content/security
      - ./config/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini   # Configuración PHP personalizada
      - ./logs/php:/var/log                                                 # Directorio de logs PHP accesible fuera del contenedor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wp_network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx_wp
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - wordpress_core:/var/www/html:ro
      - ./wordpress/plugins_custom:/var/www/html/wp-content/plugins_custom:ro
      - ./wordpress/themes:/var/www/html/wp-content/themes:ro
      - ./wordpress/uploads:/var/www/html/wp-content/uploads:ro
    environment:
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp_network

  wpcli:
    image: wordpress:cli
    container_name: wp-cli
    depends_on:
      db:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      TZ: ${TZ}
    volumes:
      - wordpress_core:/var/www/html
      - ./wordpress/plugins_custom:/var/www/html/wp-content/plugins_custom
      - ./wordpress/themes:/var/www/html/wp-content/themes
      # - ./wordpress/uploads:/var/www/html/wp-content/uploads:rw
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:rw
      - ./wordpress/security:/var/www/html/wp-content/security
      - ./config/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini   # Configuración PHP personalizada
      - ./logs/php:/var/log                                                 # Directorio de logs PHP accesible fuera del contenedor
    working_dir: /var/www/html
    entrypoint: ["wp"]
    tty: true
    stdin_open: true
    networks:
      - wp_network

volumes:
  mysql_data:            # Volumen persistente para datos de MySQL
  wordpress_core:        # Volumen persistente para archivos de WordPress

networks:
  wp_network:
    driver: bridge       # Red interna tipo bridge para comunicación entre servicios
